### ISSUE TITLE
GitHub Pagesを使って静的サイトで公開すると更に良いかもしれません

### ISSUE THREAD

**Issue by karaage0703** [tomo-makes/overcome-covid-19-jp#1]
とても良い試みですね。
GitHub Pagesという機能を使うと、READMEの内容がgithub.ioというアドレスで静的サイトとして公開できるので、より良いかもしれません。以下手順です。参考までに。

[エンジニア向け「GitHub Pages」を使った技術メモ公開のススメ](https://karaage.hatenadiary.jp/entry/2017/09/06/073000)

**Comment by tomo-makes** [comment]
@karaage0703 早速(オペラ観ながら..)GitHub Pages化させていただきました。アドバイス、記事ありがとうございます!
https://tomo-makes.github.io/overcome-covid-19-jp/
